apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-config
  namespace: default
data:
  RABBITMQ_QUEUE: 'HeatSensor'
  RABBITMQ_HOST: rabbitmq-broker
  RABBITMQ_PORT: "5672"
  RABBITMQ_PROTOCOL: "amqp"
  PORT: "3000"
  FREQUENCY: "30000"
  MAX_POINTS_IN_ONE_MESSAGE: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: producer
  namespace: default
spec:
  selector:
    app: producer
  ports:
    - name: data
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: default
  labels: 
    app: producer
spec:
  selector:
    matchLabels:
      app: producer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: nathapaulino/aps_producer
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: producer-config
        - secretRef:
            name: producers-secrets
---